# Generated by Django 2.0.7 on 2018-10-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_budget', models.IntegerField(default=0)),
                ('brand_preference', models.CharField(max_length=200)),
                ('type_of_car', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('transmission_engine', models.CharField(max_length=200)),
                ('mileage', models.CharField(max_length=200)),
                ('safety_rating', models.CharField(max_length=200)),
                ('maintenance', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_income', models.CharField(max_length=200)),
                ('type_of_housing', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('geography', models.CharField(max_length=200)),
            ],
        ),
    ]
